from constants.prompts import (
    TELEGRAM_PUBLIC_REFLECTION_PROMPT,
    COGNITIVE_ANALYSIS_PROMPT,
    INSTRUCTOR_BUILD_SCHEMA_PROMPT,
    MEDIA_IMAGE_PROMPT_BUILDER_SYSTEM_PROMPT,
    MEDIA_IMAGE_PROMPT_BUILDER_USER_TEMPLATE,
    MORAL_MATRIX_PROVIDER_PROMPT,
)

# Default configuration as dict (for backward compatibility)
DEFAULT_CONFIG = {
    "system": {
        "user_id": None,  # Will be set during initialization
        "user_name": "You",
        "char_name": "Character Name",
        "language": "en-US",
        "system_prompt": "",
        "theme": "default",
        "runtime": {
            "model_memory_profile": "low_memory_strict",
        },
    },
    "core": {
        "version": "1.0.0",
        "env": "dev",
        "debug": False,
    },
    "decision_layer": {
        "mode": "system",
        "active_provider": "ollama",
        "max_steps": 4,
        "release_after_use": True,
        "capabilities": {
            "tool": False,
            "vision": False,
            "thinking": False,
        },
        "providers": {
            "ollama": {
                "model": "llama3.2",
                "temperature": 0.2,
                "max_tokens": 512,
                "thinking": False,
            },
        },
        "instructor": {
            "build_schema": INSTRUCTOR_BUILD_SCHEMA_PROMPT,
            "include_datetime": True,
            "include_geolocation": False,
            "exclude_disabled_modules": True,
        },
    },
    "connector": {
        "tunneling": {
            "enabled": False,
            "provider": "cloudflared",
            "local_url": "http://127.0.0.1:3880",
            "local_port": 3880,
            "command_path": "",
            "public_url": "",
        }
    },
    "voice": {
        "enabled": True,
        "output_id": 0,
        "windows_output_id": 0,
        "language": "en-US",
        "use_rvc": False,
        "use_windows_output": False,
        "streaming_tts": False,
        "enable_fallback": True,
        "active_module": "edge",
        "voice_modules": {
            "elevenlabs": {
                "api_key": "",
                "voice_id": "",
                "model_id": "",
                "stability": 0.5,
                "similarity": 0.75,
            },
            "edge": {"voice_language": "en-US-JennyNeural"},
            "qwen": {
                "model_name": "Qwen/Qwen3-TTS-Flash",
                "device": "cuda",
                "dtype": "bfloat16",
                "max_seq_len": 2048,
                "language": "English",
                "temperature": 0.9,
                "top_k": 50,
                "repetition_penalty": 1.05,
                "max_new_tokens": 2048,
                "do_sample": True,
            },
        },
        "voice_language": "en-US-JennyNeural",
    },
    "stt": {
        "language": "en-US",
        "auto_detect": False,
        "provider": "whisper",
        "sherpa_onnx": {
            "model_type": "transducer",
            "encoder": "",
            "decoder": "",
            "joiner": "",
            "paraformer": "",
            "whisper_encoder": "",
            "whisper_decoder": "",
            "moonshine_preprocessor": "",
            "moonshine_encoder": "",
            "moonshine_uncached_decoder": "",
            "moonshine_cached_decoder": "",
            "tokens": "",
            "num_threads": 1,
            "provider": "cpu",
        },
    },
    "modules": {
        "vtube_studio": False,
        "whisper": True,
        "minecraft": False,
        "gaming": False,
        "alarm": False,
        "discord": False,
        "telegram": False,
        "rag": True,
        "visual": True,
    },
    "communication": {
        "priority": ["main_chat", "telegram"],
        "channels": {
            "main_chat": {
                "enabled": True,
                "allow_fallback": False,
            },
            "telegram": {
                "enabled": True,
                "allow_fallback": False,
            },
        },
    },
    "audio": {
        "input_device_id": 0,
        "sample_rate": 16000,
        "channels": 1,
        "chunk_size": 1024,
        "enable_vad": True,
        "vad_threshold": 0.5,
        "silence_timeout": 3.0,
        "min_audio_length": 0.5,
        "max_audio_length": 120.0,
        "trigger_words": [],
        "ignore_trigger_words": True,
    },
    "vision": {
        "enabled": True,
        "active_provider": "apple_vision",
        "monitor_index": 0,
        "fps": 5,
        "buffer_sec": 4,
        "downscale_width": 1280,
        "yolo_enabled": False,
        "ocr_lang": "eng",
        "ocr_min_conf": 70,
        "ocr_max_lines": 5,
        "region": None,
        "capture_mode": "monitor",
        "window_title": "",
        "window_process": "",
        "debug_save": False,
        "debug_path": "temp/vision",
        "vision_modules": {
            "apple_vision": {"model_id": "apple/FastVLM-1.5B", "max_tokens": 128},
            "llava": {"model_id": "llava-hf/llava-1.5-7b-hf", "max_tokens": 128},
            "ollama_vision": {
                "model": "llava:latest",
                "max_tokens": 512,
                "probe_enabled": True,
                "probe_cache_seconds": 300,
                "image_format": "PNG",
                "keep_alive": "5m",
                "use_main_model_context": False,
            },
            "llama_cpp_vision": {
                "enabled": False,
                "base_url": "http://127.0.0.1:8080",
                "model": "",
                "max_tokens": 512,
                "request_timeout": 120,
                "ping_timeout": 3.0,
                "image_format": "PNG",
            },
        },
    },
    "rag": {
        "enabled": True,
        "embedding_model": "all-MiniLM-L6-v2",
        "vector_db_path": "./data/vector_db",
        "chunk_size": 500,
        "chunk_overlap": 50,
        "top_k": 5,
        "similarity_threshold": 0.7,
        "enable_caching": True,
        "cache_ttl": 60,
        "search_strategy": {
            "session_context": {
                "enabled": True,
                "max_messages": 32,
                "look_back_to_today": True,
            },
            "daily_summary": {"enabled": True, "look_back_days": 7, "use_tags": True},
            "long_term_memory": {
                "enabled": True,
                "vector_search": True,
                "graph_search": True,
                "priority_rules": True,
            },
            "fallback": {"ask_user": True, "auto_learn": True},
        },
        "memory": {
            "facts": {
                "enabled": True,
                "priority_rules": ["user", "name", "person"],
                "auto_update": True,
            },
            "graph": {"enabled": True, "relationships": True, "inference": True},
        },
        "retrieval": {
            "recent": {"limit": 32},
            "session": {
                "enabled": True,
                "window": "day",
                "idle_gap_minutes": 90,
                "max_messages": 512,
                "chunk_size": 32,
            },
            "keyword": {
                "enabled": True,
                "max_candidates": 8,
                "min_score": 0.2,
                "min_overlap": 0.25,
                "boost_user": 1.05,
                "boost_assistant": 0.95,
                "stopwords": [
                    "это",
                    "как",
                    "или",
                    "если",
                    "when",
                    "then",
                    "with",
                    "что",
                    "and",
                    "the",
                ],
            },
            "vectors": {
                "primary": "embed768",
                "profiles": {
                    "embed768": {
                        "label": "768d • nomic-embed-text",
                        "enabled": True,
                        "provider": "ollama",
                        "model": "nomic-embed-text",
                        "endpoint": "http://localhost:11434/api/embeddings",
                        "timeout": 30,
                        "max_retries": 2,
                        "retry_backoff": 0.75,
                        "top_k": 8,
                        "threshold": 0.9,
                    },
                    "embed384": {
                        "label": "384d • all-MiniLM-L6-v2",
                        "enabled": True,
                        "provider": "st",
                        "model": "all-MiniLM-L6-v2",
                        "device": "cpu",
                        "top_k": 10,
                        "threshold": 0.9,
                    },
                },
            },
            "short_term": {
                "enabled": True,
                "threshold": 0.75,
                "lookback_days": 7,
            },
            "emotional": {
                "enabled": True,
                "lookback_days": 14,
                "limit": 5,
            },
            "rerank": {
                "enabled": True,
                "top_n": 6,
                "use_primary_rerank": True,
                "boost_recency": 0.15,
                "weights": {
                    "embedding": 0.65,
                    "keyword": 0.25,
                    "short_term": 0.1,
                },
            },
        },
        "lore": {
            "top_k": 3,
            "similarity_threshold": 0.7,
        },
    },
    "analyzer": {
        "enabled": True,
        "active_provider": "ollama",
        "fallback_order": [],
        "release_after_use": True,
        "system_prompt": COGNITIVE_ANALYSIS_PROMPT,
        "providers": {
            "openrouter": {
                "api_key": "",
                "model": "",
                "temperature": 0.1,
                "max_tokens": 1024,
            },
            "ollama": {
                "model": "llama3.2",
                "temperature": 0.1,
                "max_tokens": 1024,
                "thinking": False,
            },
            "llama_cpp": {
                "enabled": False,
                "base_url": "http://127.0.0.1:8080",
                "model": "",
                "temperature": 0.1,
                "max_tokens": 1024,
                "request_timeout": 120,
            },
        },
    },
    "moral": {
        "enabled": True,
        "active_provider": "ollama",
        "fallback_order": ["openrouter", "heuristic"],
        "release_after_use": True,
        "system_prompt": MORAL_MATRIX_PROVIDER_PROMPT,
        "decay": {
            "enabled": True,
            "global_rate": 0.05,
        },
        "current_state": {
            "current_emotion": "peace",
            "emotion_intensity": 0.34,
            "emotion_vector": {
                "longing": 0.10,
                "joy": 0.28,
                "frustration": 0.08,
                "sadness": 0.08,
                "embarrassment": 0.05,
                "anxiety": 0.06,
                "peace": 0.34,
                "confusion": 0.06,
                "pride": 0.10,
                "resentment": 0.03,
                "tenderness": 0.22,
                "jealousy": 0.04,
            },
            "trigger": "начальное спокойное состояние",
            "associated_events": [],
            "influence": {"initiative": 0.0, "tone": "ровный", "reaction_delay": "0s"},
        },
        "providers": {
            "heuristic": {},
            "ollama": {
                "model": "llama3.2",
                "temperature": 0.6,
                "max_tokens": 512,
                "thinking": False,
            },
            "openrouter": {
                "api_key": "",
                "model": "openai/gpt-4o-mini",
                "temperature": 0.6,
                "max_tokens": 512,
            },
            "llama_cpp": {
                "enabled": False,
                "base_url": "http://127.0.0.1:8080",
                "model": "",
                "temperature": 0.6,
                "max_tokens": 512,
                "request_timeout": 120,
            },
        },
    },
    "memory": {
        "deep_memory_enabled": True,
        "force_deep_memory": False,
        "recent_limit": 32,
        "similarity_threshold": 0.7,
        "session_window": "day",
        "session_enabled": True,
        "embedding_provider": "auto",
        "embedding_model": "nomic-embed-text",
        "consolidation": {
            "importance_threshold": 0.2,
            "judge": {
                "enabled": False,
                "provider": "ollama",
                "model": "",
                "temperature": 0.0,
                "max_tokens": 512,
                "request_timeout": 60,
            },
        },
    },
    "synthesis": {
        "active_provider": "core",
        "sd_webui": {
            "enabled": False,
            "base_url": "http://127.0.0.1:7860",
            "bearer_token": "",
            "timeout_sec": 180,
            "checkpoint": "",
            "sampler_name": "DPM++ 2M",
            "scheduler": "Automatic",
            "cfg_scale_default": 2.0,
        },
        "comfyui": {
            "enabled": False,
            "base_url": "http://127.0.0.1:8188",
            "websocket_url": "ws://127.0.0.1:8188/ws",
            "timeout_sec": 180,
            "default_workflow": "",
            "default_model": "",
            "sampler": "euler",
            "scheduler": "normal",
            "steps": 30,
            "cfg": 7.0,
            "width": 1024,
            "height": 1024,
            "aspect_ratio": "1:1",
        },
        "diffusers": {
            "enabled": True,
            "device": "auto",
            "default_model": "z_image_turbo",
            "local_models_path": "storage/models/image-generation",
            "cache_dir": "",
            "torch_dtype": "auto",
            "keep_loaded": True,
            "sampler": "euler",
            "scheduler": "normal",
            "steps": 30,
            "cfg": 7.0,
            "width": 1024,
            "height": 1024,
            "aspect_ratio": "1:1",
            "allow_comfyui_fallback": True,
        },
        "prompting": {
            "enabled": True,
            "max_attempts": 3,
            "assess_enabled": True,
            "retry_enabled": True,
            "quality_threshold": 0.72,
            "appearance_prompt": "",
            "default_negative_prompt": "(text:2), (signature:2), raw photo",
            "image_prompt_builder_system_prompt": MEDIA_IMAGE_PROMPT_BUILDER_SYSTEM_PROMPT,
            "image_prompt_builder_user_template": MEDIA_IMAGE_PROMPT_BUILDER_USER_TEMPLATE,
            "visual_profile": {
                "character_name": "PAI",
                "appearance_textarea": "",
                "default_outfit": "",
                "default_environment": "",
                "style_preset": "anime",
                "render_profile": "default_anime",
                "selfie_bias": 0.85,
                "environment_bias": 0.10,
                "symbolic_bias": 0.05,
                "anti_repetition_strength": 0.65,
                "use_time_of_day": True,
                "use_season": True,
                "use_weather": True,
                "use_relation_state": True,
                "use_recent_topics": True,
                "selfie_composition_base": "",
                "selfie_composition_pool_override": "",
                "environment_composition_pool_override": "",
                "allow_self_images": True,
                "allow_environment_images": True,
                "allow_symbolic_images": True,
            },
            "per_character_visual_profiles": {},
            "scenarios": {
                "sandbox": {
                    "title": "Sandbox",
                    "enabled": True,
                    "use_prompt_builder": True,
                    "review_generated_image": True,
                    "use_visual_intent": False,
                    "prompt_policy": "",
                    "style_prompt": "",
                    "negative_prompt": "",
                    "system_prompt": "",
                },
                "telegram_command": {
                    "title": "Telegram command",
                    "enabled": True,
                    "use_prompt_builder": True,
                    "review_generated_image": True,
                    "use_visual_intent": True,
                    "prompt_policy": "",
                    "style_prompt": "",
                    "negative_prompt": "",
                    "system_prompt": "",
                },
                "telegram_tool": {
                    "title": "Telegram tool",
                    "enabled": True,
                    "use_prompt_builder": True,
                    "review_generated_image": True,
                    "use_visual_intent": True,
                    "prompt_policy": "",
                    "style_prompt": "",
                    "negative_prompt": "",
                    "system_prompt": "",
                },
                "main_chat": {
                    "title": "Main chat",
                    "enabled": True,
                    "use_prompt_builder": False,
                    "review_generated_image": False,
                    "use_visual_intent": True,
                    "prompt_policy": "",
                    "style_prompt": "",
                    "negative_prompt": "",
                    "system_prompt": "",
                },
            },
        },
    },
    "telegram": {
        "enabled": False,
        "mode": "mtproto",  # mtproto | bot
        "api_id": 0,
        "api_hash": "",
        "session_name": "z_waif",
        "session_dir": "data/telegram",
        "phone_number": "",
        "bot_token": "",
        "queue_size": 256,
        "history_max_messages": 24,
        "sync": {
            "enabled": True,
            "startup_reindex_enabled": True,
            "connect_reindex_enabled": True,
            "max_chats": 32,
            "messages_per_chat": 80,
        },
        "persona_bindings": {
            "chat_character_map": {},
        },
        "lockdown": {
            "enabled": False,
            "owner_chat_id": 0,
        },
        "presence": {
            "enabled": True,
            "auto_offline_after_send": True,
        },
        "routing": {
            "allow_private": True,
            "allow_groups": True,
            "allow_channels": True,
            "write_private": True,
            "write_groups": True,
            "write_channels": False,
            "read_only_non_private": True,
            "groups_require_mention": False,
            "allowed_chat_ids": [],
        },
        "write_policy": {
            "allow_private": True,
            "allow_groups": False,
            "allow_channels": False,
            "allowed_private_chat_ids": [],
            "denied_chat_ids": [],
            "sandbox_chat_ids": [],
        },
        "channels": {
            "read_enabled": True,
            "mark_read_enabled": True,
            "reflect_enabled": False,
            "reflection_instruction": "Reflect shortly on key facts and implications from this channel post.",
        },
        "reflection": {
            "enabled": True,
            "source_chat_ids": [],
            "source_chat_kinds": ["channel", "group"],
            "target_chat_id": 0,
            "prompt": TELEGRAM_PUBLIC_REFLECTION_PROMPT,
            "include_source_excerpt": True,
            "include_source_link": True,
            "max_source_excerpt_chars": 800,
            "max_reflection_length": 1200,
            "min_source_text_chars": 25,
            "cooldown_per_source_chat_seconds": 90,
            "dedup_enabled": True,
        },
        "quiet_hours": {
            "enabled": True,
            "start": "00:00",
            "end": "09:00",
        },
        "anti_spam": {
            "per_chat_max_messages": 5,
            "global_max_messages": 24,
            "window_seconds": 15.0,
            "min_delay_seconds": 0.7,
            "typing_delay_enabled": True,
            "typing_ms_per_char": 22.0,
            "typing_min_ms": 220.0,
            "typing_max_ms": 2200.0,
        },
        "anti_repeat": {
            "history_size": 32,
            "similarity_threshold": 0.92,
            "jaccard_threshold": 0.88,
            "semantic_enabled": True,
            "semantic_history_size": 32,
            "semantic_max_similarity_threshold": 0.75,
            "semantic_avg_similarity_threshold": 0.73,
            "semantic_provider": "auto",
            "semantic_model": "nomic-embed-text",
            "enforce_for_incoming_dialogs": False,
            "retry_on_block": True,
            "retry_attempts": 1,
            "retry_use_memory": True,
            "retry_memory_chars": 1200,
        },
        "initiative": {
            "enabled": False,
            "check_every_seconds": 60,
            "idle_minutes": 60,
            "min_gap_minutes": 30,
            "max_proactive_per_day": 3,
            "morning_checkin_enabled": True,
            "evening_checkin_enabled": True,
            "daily_digest_enabled": True,
            "daily_digest_window_start": "20:00",
            "daily_digest_window_end": "22:00",
            "owner_chat_only": True,
            "bootstrap_from_catalog": True,
            "bootstrap_max_chats": 64,
            "allow_private": True,
            "allow_groups": False,
            "prompt_template": "You have not heard from this chat for {idle_minutes} minutes. Send one short warm proactive message, if appropriate.",
        },
        "autonomous_inbox": {
            "enabled": False,
            "check_every_seconds": 45,
            "max_candidates": 8,
            "max_actions_per_cycle": 2,
            "include_private": True,
            "include_groups": True,
            "include_channels": True,
            "private_pause_probability": 0.2,
            "prompt_template": "You are online and received unread events in Telegram. Choose one action: open chat, answer, read channel, or pause.",
        },
        "orchestration": {
            "enabled": False,
            "allow_llm_tool_actions": False,
            "max_rounds": 4,
            "max_tool_output_chars": 3000,
            "max_manual_sends_per_turn": 3,
            "require_tool_call": False,
            "max_no_tool_retries": 2,
            "tools": {
                "get_telegram_chats": True,
                "open_chat_by_id": True,
                "get_chat_photo": True,
                "ask_memory": True,
                "take_photo": True,
                "send_generated_photo": True,
                "send_telegram_message": True,
                "ask_google": True,
                "wait_pause": True,
            },
        },
        "image": {
            "enabled": True,
            "command_prefix": "/image",
            "default_model": "",
            "negative_prompt": "",
            "width": 1024,
            "height": 1024,
            "num_inference_steps": 9,
            "guidance_scale": 0.0,
            "caption_template": "",
            "autonomous_random_enabled": False,
            "autonomous_random_probability": 0.5,
        },
        "media": {
            "ingest_enabled": True,
            "max_incoming_media_bytes": 2000000,
        },
        "formatting": {
            "max_chars_per_message": 700,
            "max_messages_per_turn": 3,
        },
    },
    "api": {
        "type": "Ollama",
        "streaming": True,
        "model": "llama3.2",
        "visual_model": "apple/FastVLM-1.5B",
        "visual_model_options": ["apple/FastVLM-1.5B"],
        "token_limit": 4096,
        "message_pair_limit": 4,
        "active_provider": "ollama",
        "fallback_order": [],
        "providers": {
            "ollama": {
                "model": "llama3.2",
                "temperature": 0.85,
                "max_tokens": 2048,
                "streaming": True,
                "base_url": "http://localhost:11434",
            },
            "openrouter": {
                "api_key": "",
                "model": "openai/gpt-4o-mini",
                "temperature": 0.85,
                "max_tokens": 2048,
                "base_url": "https://openrouter.ai/api/v1",
            },
            "transformers": {
                "model": "",
                "temperature": 0.85,
                "max_tokens": 2048,
                "streaming": True,
                "device_map": "auto",
                "torch_dtype": "auto",
                "trust_remote_code": True,
                "low_cpu_mem_usage": True,
                "do_sample": True,
                "top_p": 0.9,
                "top_k": 50,
                "repetition_penalty": 1.1,
                "keep_loaded": True,
                "source": "huggingface",
            },
            "llama_cpp": {
                "enabled": False,
                "model": "",
                "base_url": "http://127.0.0.1:8080",
                "streaming": True,
                "request_timeout": 300,
                "stream_timeout": 600,
                "temperature": 0.85,
                "max_tokens": 2048,
                "top_p": 0.9,
                "top_k": 50,
                "min_p": 0.05,
                "repeat_penalty": 1.1,
            },
        },
    },
    "web_runtime": {
        "enabled": True,
        "extractor_provider": "basic",
        "timeout": 8,
        "max_chars": 12000,
        "max_bytes": 2000000,
        "allow_private_urls": False,
        "search": {
            "enabled": False,
            "provider": "none",
        },
        "browser": {
            "enabled": False,
            "provider": "none",
        },
    },
    "generate_settings": {
        "temperature": 0.85,
        "min_p": 0.05,
        "top_p": 0.9,
        "top_k": 50,
        "repeat_penalty": 1.2,
        "stop": None,
        "num_predict": 2048,
        "normalize_messages": False,
        "unbounded_reasoning_if_supported": True,
        "reasoning_headroom_tokens": 512,
        "name": "Default",
        "description": "Basic generation parameters",
    },
}
